### ISSUE TITLE
세탁기 사용현황 보는 방법 수정

### ISSUE THREAD

**Issue by LEE-DA-EUN** [LIMDANBI/ERICA_This-is-our-first-step.#1]
사이트에 들어갔을때 좀더 직관적으로 사용유무를 파악할 수 있게 수정하는 게 좋을 것 같아요.

**Comment by LIMDANBI** [comment]
요구 사항 반영해서 웹화면 조금 수정했어요! 사용중이면 빨강색, 사용 가능하면 초록색으로 화면에 띄우도록 간단하게 몇가지 수정했습니다~

**Comment by LEE-DA-EUN** [comment]
네 확인했어요!!! 눈에 더 잘보이게 잘 수정됬네요!!
