### ISSUE TITLE
와이파이 통신모듈

### ISSUE THREAD

**Issue by LIMDANBI** [LIMDANBI/ERICA_This-is-our-first-step.#2]
와이파이 통신 모듈이 불안정한거 같아요 ㅜㅜ 아두이노 진동센서는 잘 감지 하는데 통신이 되지 않네요 ㅜ

**Comment by LEE-DA-EUN** [comment]
다른 모듈로도 해봤는데 잘안되네요ㅠㅠ 와이파이만의 문제가 아닌것 같아요!ㅠ 라즈베리파이로 하면 해결될것같습니다 ㅠㅠ!
